---
title: "day3_markdown"
author: "Martin Lopatka"
date: "May 9, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadPackages}
library(mvoutlier)
library(knitr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(car)
library(MVN)
library(lattice)
```

```{r}
howells <- read.csv("~/repos/r_course/data/howells 2.csv") # load howells
scatterplotMatrix(howells[5:8])
# visualize the data as a scattermatrix

aq.plot(howells[5:8])
```

```{r normalityTest}
uniPlot(howells[5:7])
irisDat <- data(iris)
mardiaTest(howells[5:6])
mardiaTest(howells[5:7])
mardiaTest(howells[5:8])
mardiaTest(iris[2:3])
mardiaTest(iris[1:3])

results <- mardiaTest(iris[1:2])
mvnPlot(results, type="contour", default=TRUE)

uniNorm(howells[5:6], type="SW", desc=TRUE)

```

```{r honmoskedacicity}
# bartletts
# levene
# flinger-killeen
growth <- read.csv("~/repos/r_course/data/growth.csv")
bartlett.test(FMXLN..mm. ~ SEX, data = growth)

```

```{r linearity}
scatterplotMatrix(howells[12:15])
```