---
title: "day3_part2_markdown"
author: "Martin Lopatka"
date: "May 9, 2016"
output: html_document
---

```{r loadPackages}
library(mvoutlier)
library(knitr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(car)
library(MVN)
library(Hmisc)
library(psych)
#library(lattice)
```

```{r excercise1}
growth <- read.csv("~/repos/r_course/data/growth.csv")
names(growth)
# change the names properly
names(growth)<-c("id","sex","fmxl","age")
scatterplotMatrix(growth[3:4])

```

```{r}
outliers <- growth[growth$age>40,]
rest <- growth[growth$age<40,]
plot_handle <- ggplot(rest, aes(x=age, y=fmxl)) + geom_point()

print(plot_handle)
```

```{r excercise2}
howells <- read.csv("~/repos/r_course/data/howells 2.csv")
postcran <- read.csv("~/repos/r_course/data/goldman_pc.csv")
    
#prac1 <- mean(howells[howells$Population=="EASTER I","GOL"])
prac1 <- howells %>% select(Sex, GOL, Population) %>% filter(Sex == 'F', Population == "EASTER I")
prac1 <- mean(prac1$GOL)
cat('the mean GOL for Easter Island Females in the howells dataset is', prac1)

prac2 <- sum(postcran$Location=="Alaska, United States")
cat('the number of Alaskan data points is', prac2)

describeBy(howells$XCB,howells$Sex)

```

```{r}
pubes1 <- read.csv("~/repos/r_course/data/Pubes1.csv")
pubes2 <- read.csv("~/repos/r_course/data/Pubes2.csv")
goldman <- read.csv("~/repos/r_course/data/goldman_pc.csv")

summary(goldman$Sex)
postcran <- goldman %>% select(Inst,Sex,lhml,lheb,lhhd) %>% filter(Sex %in% c(0,1), Inst %in% c('KU','MNdAE','NHM', 'SfAP')) %>% na.omit()

```

```{r}
t.test(postcran$lhml ~ postcran$Sex)
# two-taled t test for lhml grouped by sex
```
