---
title: "day4_afternoon_markdown"
author: "Martin Lopatka"
date: "May 10, 2016"
output: html_document
---

```{r libraries}
library(ggplot2)
library(magrittr)
library(corrplot)
library(dplyr)
library(car)
library(psych)
library(pwr)
library(vcd)
library(gmodels)
library(gvlma)
```

```{r}
#bulletFEATS <- read.csv("/Users/Martin/Dropbox/bulletFeats/v1-30/x.csv")
#bulletTOW <- read.csv("/Users/Martin/Dropbox/bulletFeats/v1-30/y.csv")
#fit <- lm(data.frame(bulletTOW) ~ bulletFEATS$X2859.8)
```


```{r}
summary(fit <- lm(weight ~ height, data=women))
# Weight = −87.52 + 3.45(Height)
# interpretation: ~99% of the variability in weight can be predicted by the height.
```

```{r}
hwReg <- read.csv("~/repos/r_course/data/height_weight.csv")
names(hwReg) <- c("nr","age","height","weight")
hwReg %<>% filter(as.numeric(hwReg$height) > 750 & as.numeric(hwReg$weight) < 450)

x_w<-as.numeric(hwReg$weight)
y_h<-as.numeric(hwReg$height)
fithw <- lm(y_h ~ x_w)
summary(fithw)
hwReg <- data.frame(y_h,x_w)
ggplot(hwReg, aes(x=x_w, y=y_h))+ geom_point() + geom_abline(intercept=840.25133, slope=1.99293)
plot(fithw)
influencePlot(fithw, id.method="noteworthy")
cook <- cooks.distance(fithw)
plot(cook)
```

```{r}
ggplot(as.data.frame(fithw[2]), aes(x=residuals)) + geom_histogram(aes(y=..density..), binwidth=5, color = "black", fill = "goldenrod")

ks.test(as.data.frame(fithw$residuals), "pt",df=nrow(mtcars)-2-2) 
gvlma(fithw)

ncvTest(fithw)
spreadLevelPlot(fithw)
```

```{r}
stats_qq <- qqPlot(fithw)
spreadLevelPlot(fithw)
ncvTest(fithw)
```
A significant p-value for this test suggests heteroscedasticity (violation!), therefore the observed p-value suggest we are OK for the honoscecadicity assumption


```{r}
fit2<-fithw

fit2_PIpred <- predict(fit2, newdata=hwReg, interval="prediction")
fit2_CIpred <- predict(fit2, newdata=hwReg, interval="confidence")

fit2_PIpred <- as.data.frame(fit2_PIpred)
fit2_CIpred <- as.data.frame(fit2_CIpred)

names(fit2_PIpred) <- c("Fit Values","Lower Prediction Interval","Upper Prediction Interval")
names(fit2_CIpred) <- c("Fit Values","Lower Confidence Interval","Upper Confidence Interval")

thing<-merge(fit2_CIpred,fit2_PIpred,by="Fit Values")
```

```{r visualizingResults}
ggplot(hwReg, aes(x=height, y=weight)) + labs(x=labx,y=laby)+ geom_point(alpha=0.6,cex=2.5,shape=21)
+ geom_point(data=hw, aes(x=height, y=weight), cex=2, col="goldrod")
+ geom_line(data = fit_predict, aes(x = height, y = fit, lty = "Fit Values")) 
+ geom_line(data = fit_predict, aes(x = height, y = Lwr_PI, lty= "95% PI"))
+ geom_line(data = fit_predict, aes(x = height, y = Upr_PI, lty= "95% PI")) 
+ scale_linetype_manual("", breaks=c("Fit", "95% PI"), values=c(3,2)) 

```
