---
title: "day5_markdown"
author: "Martin Lopatka"
date: "May 11, 2016"
output: html_document
---

```{r libraries}
library(ggplot2)
library(magrittr)
library(dplyr)
library(car)
library(lme4)
library(lmerTest)
```

```{r loadData}
longDat <- read.csv("~/repos/r_course/data/longdata.csv")
```

```{r}
# E(y) = B_0 + B_1*X1_i + e
# standard linear equation
# nested data: 2 levels of nesting
# smallest unit of analysis.

# Fixed Effects: the effect applies equally to all participants, therefore the slope must be equal, but the intercept will be flexible.
# Random Effects: the effect will differe for each individual in the population.
# Mixed effects both fixed, and random

# level 1 prediction
# Y_i,j = growth + error
# Y_ij = n_0i + n_1iX_ij + e+ij

# level 2 prediction
# n_0i = Y_00 + g_0i
# Y_00 is the mean initial status or popuation avergae for all intercepts pertaining to one individual
# g_0i is the level 2 random effect of initial status (intercept) error term for individuals fromt he group mean.

# random intercepts fixed slopes (mean of the slopes for all groups = y_00)
# discrepancy between each indivdual and the mean (y_00) is the 

# random slopes are inputed into g_1i
# mean of slopes should be ~0
# indivisual slopes for one person lead to an individual's random effect 
# which will be different per individual (difference in global slope and individual group slope)
```

```{r}

mdl1 <- lmer(longDat$depsev~1+(1|longDat$ID),data=longDat)
# ID is the individual, so this is the nesting (level 2) variable
# depSev = the thing to be observed
# (Intercept)  5.07786  corresponds to the average Time 0 depresion level for the entire population!

# 0.7021/(0.7021+1.2218) corresponds to the intraclass correlation coefficient
# level 1 variance is lower than the level 2 error
# i.e. 36% of the total variatino in depression severity is accounted for by the nesting within persons
# so high predictive value from nested structure!
summary(mdl1)
```

```{r}
# conditional models
# Y_ij = n_0i + n_1iX_ij + e+ij
# level 2 changes: n_0i = Y_00 + Y_01 * Zi + g_oi
# Z can be mapped to a 0/1 value to make use of categorical variables intializing the random effect in some population subset

mdl2 <- lmer(longDat$depsev~1 + longDat$mood + (1|longDat$ID),data=longDat) 
summary(mdl2)

#  longDat$mood 4.863e-01  2.015e-02 1.965e+03   24.13   <2e-16 ***
# Therefore the fixed effect of mood on depression is 4.863e-01 wiht a p value of <2e-16

# Also the variance in level 1 has changed drastically by the addition of an additional predictor vriable:
# 0.8406/(0.8406+0.9304)
# so now 0.4746471 fo the total variance in 

mdl3 <- lmer(longDat$depsev~1 + longDat$mood + (1+longDat$mood|longDat$ID),data=longDat) 
summary(mdl3)
# now we ahve added an additional random effect for the slope fo the mood.
# at the level 1 (the ID level)
# (2.99952+0.02599)/(2.99952+0.02599+0.89492) so now 0.7717291 of the total variance in the  depression severity can be explained by the heirarchical nature of the data, daily mood, both average initial and the rate of daiy change in the daily mood throughout the study period.
# individual (ID) plus the daily mood and growth status of daily mood over time. 

```

